name: CI
on:
  push:
    branches:
      - master
      - for-master
    tags:
      - v*
  pull_request:
    branches:
      - master
      - for-master
jobs:
  linux:
    uses: ./.github/workflows/_common.yml
    with:
      os: ubuntu-latest

  macos:
    uses: ./.github/workflows/_common.yml
    with:
      os: macos-latest

  freebsd:
    uses: ./.github/workflows/_freebsd.yml

  openbsd:
    uses: ./.github/workflows/_openbsd.yml

  solaris:
    uses: ./.github/workflows/_solaris.yml
